#!/usr/bin/with-contenv sh

if [ -n "$CLOUDFLARE_DNS_TUNNEL_UUID" ]; then
    cloudflared tunnel run ${CLOUDFLARE_DNS_TUNNEL_UUID}
elif [ -n "$CLOUDFLARE_TUNNEL_JWT" ]; then
    cloudflared tunnel run --token ${CLOUDFLARE_TUNNEL_JWT}
fi
