name: Docker Publish On Demand

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Version to push'     
          required: true

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.version }}

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install NPM packages
      run: yarn ci

    - name: Build project
      run: yarn build

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
      id: buildx
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    -  name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
        context: .
        push: true
        tags: wovalle/angelos:latest,wovalle/angelos:${{ github.event.inputs.version }}
