name: Publish

on:
  push:
    branches: [main, next]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: true

    - name: Build project
      run: pnpm build

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Action For Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2.6.0
      with: 
        semantic_version: 18
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Was the version released?
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo "New Released version: ${{ steps.semantic.outputs.new_release_version }}"
    
    - name: Docker Login
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    
    - name: Build image
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        docker build -t ghcr.io/wovalle/angelos:${VERSION} .
      env:
        VERSION: ${{ steps.semantic.outputs.new_release_version }}

    - name: Tag latest
      if: steps.extract_branch.outputs.branch == 'main'
      run: |
        docker tag ghcr.io/wovalle/angelos:${VERSION} ghcr.io/wovalle/angelos:latest
      env:
        VERSION: ${{ steps.semantic.outputs.new_release_version }}
    
    - name: Tag next
      if: steps.extract_branch.outputs.branch == 'next'
      run: |
        docker tag ghcr.io/wovalle/angelos:${VERSION} ghcr.io/wovalle/angelos:next
      env:
        VERSION: ${{ steps.semantic.outputs.new_release_version }}
    
    - name: Deploy image
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        docker push --all-tags ghcr.io/wovalle/angelos
      env:
        VERSION: ${{ steps.semantic.outputs.new_release_version }}