name: Publish Next

on:
  push:
    branches: [next]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: true

    - name: Build project
      run: pnpm build

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{github.repository}}:next
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
